import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import SessionAuthprovider from "@/context/SessionAuthprovider";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressContentEditableWarning className={sora.className}>
        {children}
        {/* <SessionAuthprovider>{children}</SessionAuthprovider> */}
      </body>
    </html>
  );
}
